name: Generate HTML from JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          mkdir output
          python3 scripts/generate.py

      - name: Checkout pages branch
        uses: actions/checkout@v4
        with:
          ref: pages
          path: pages-branch

      - name: Delete existing files and folders
        run: |
          cd pages-branch
          rm -rf *
          cd ..

      - name: Copy generated HTML to pages branch
        run: |
          cp -r output/* pages-branch/
          cd pages-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update HTML from JSON" || echo "Nothing to commit"
          git push origin pages
